background_image:
  type: string
  default: default
  description: Enter image url

tile_background: false

no_background_image:
  default: false
  description: Disable the background image and tiling settings above.
